version: '3'

tasks:
  run:backend:
    cmds:
      - cd backend/src && rye run uvicorn main:app --reload
    desc: "Start FastAPI server"
  
  run:frontend:
    cmds:
      - cd frontend && bun run dev
    desc: "Start React app"
  
  test:backend:
    cmds:
      - cd backend && PYTHONPATH="." rye run pytest -vv -s
    desc: "Run tests for FastAPI server"
  
  clean:pycache:
    cmds:
      - find . -name "__pycache__" -type d -exec rm -r {} +
    desc: "Remove pycache directories"